#include "settingswindow.h"
#include "consolewindow.h"
#include "qjsondocument.h"
#include "themeeditor.h"
#include "ui_settingswindow.h"
#include "messagewindow.h"
#include "autodrawer.h"
#include "downloadthemes.h"
#include <QDesktopServices>
#include <QUrl>
#include <QFile>
#include <QJsonParseError>
#include <QJsonObject>
#include <QStandardPaths>
#include <QDirIterator>
#include <QApplication>
#include <QProcess>
auto PathAD = QStandardPaths::writableLocation(QStandardPaths::AppDataLocation) + "/AutoDrawer";
bool indexReady = false;

SettingsWindow::SettingsWindow(QWidget *parent) :
    QMainWindow(parent),
    ui(new Ui::SettingsWindow)
{
    indexReady = false;
    ui->setupUi(this);
    setWindowFlags(Qt::Widget | Qt::FramelessWindowHint);
    setParent(0);
    setAttribute(Qt::WA_NoSystemBackground, true);
    setAttribute(Qt::WA_TranslucentBackground, true);
    QFile inFile(PathAD+"/user.cfg");
    inFile.open(QIODevice::ReadOnly|QIODevice::Text);
    QByteArray data = inFile.readAll();
    QJsonParseError errorPtr;
    QJsonDocument doc = QJsonDocument::fromJson(data, &errorPtr);
    QJsonObject rootObj = doc.object();
    QString theme = rootObj.value("theme").toString();
    reloadThemes(theme);
    reloadList();
    ui->ThemeCombo->setCurrentIndex(ui->ThemeCombo->findText(theme));
    ui->PrinterBox->setChecked(rootObj["printer"].toBool());
    ui->LogBox->setChecked(rootObj["logs"].toBool());
    ui->OffsetBox->setChecked(rootObj["offset_enabled"].toBool());
    ui->intervalTextBox->setEnabled(rootObj["offset_enabled"].toBool());
    ui->intervalTextBox->setText(QString::number(rootObj["offset_x"].toInt()));
    ui->intervalTextBox_2->setEnabled(rootObj["offset_enabled"].toBool());
    ui->intervalTextBox_2->setText(QString::number(rootObj["offset_y"].toInt()));
    inFile.close();
    indexReady = true;
}

SettingsWindow::~SettingsWindow()
{
    delete ui;
}

void SettingsWindow::reloadThemes(QString theme){

    QJsonObject preview;
    QJsonObject rootObj;
    if (theme == "dark") {
        extern QString darkJson;
        QByteArray br = darkJson.toUtf8();
        QJsonDocument doc = QJsonDocument::fromJson(br);
        rootObj = doc.object();
        preview = rootObj["settings"].toObject();
    } else if (theme == "light"){
        extern QString lightJson;
        QByteArray br = lightJson.toUtf8();
        QJsonDocument doc = QJsonDocument::fromJson(br);
        rootObj = doc.object();
        preview = rootObj["settings"].toObject();
    } else if (QFile::exists(PathAD+"/themes/"+theme+".drawtheme") ){
        QFile inFile2(PathAD+"/themes/"+theme+".drawtheme");
        inFile2.open(QIODevice::ReadOnly|QIODevice::Text);
        QByteArray themeData = inFile2.readAll();
        QJsonParseError errorPtr;
        QJsonDocument docT = QJsonDocument::fromJson(themeData, &errorPtr);
        rootObj = docT.object();
        preview = rootObj["settings"].toObject();
        inFile2.close();
    }
    QPixmap in;
    auto lightmode = rootObj.value("light-icons").toString();
    if(lightmode=="true"){
        in.loadFromData(QByteArray::fromBase64("iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAMAAACdt4HsAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAC91BMVEUAAAD7/fv8/vv7/fr8/vr8/fv8/vz7/vv6//v9//v5//v//+3j/+r8/frw///5/ff7/vqRrOP0//ft+fL6//j8/Pz6/vrt/P/2//j7/fv8/vr8/vv8/vv8/vv8/fr8/vv8/vr8/fv8/vv8/vv8/fv8/vv8/vv8/vv8/vv8/fv7/vv8/vv8/vv7/fr8/vv8/vv8/vv8/vv8/vv8/vv8/vv7/vv8/vv8/vv8/vv7/vv7/fz7/vv8/vv8/vv8/vv8/vv7/vv7/vv8/fv8/vr8/fr8/vv8/vv8/vv8/vr8/vr8/vz7/fv8/vv8/vv7/fv8/vv8/vv7/fv9/vv8/vr8/vv8/vv8/vv8/vv8/vv8/vv8/vv8/vv8/vv8/vv8/vv8/vv7/fv7/vr8/vv7/fv8/fv8/vv8/vv8/vr8/fv8/vv8/vv8/vv8/vv7/vv7/vv8/vv8/vv7/vv7/vr7/vr7/fv7/fv7/vv7/vv7/vr7/fv7/fv8/fv8/fv8/vv8/vv8/vv8/vv8/vv8/vr7/fv7/fv7/fv8/vv8/fv8/vv8/vv8/fv8/vv7/vv7/fv7/fv7/fv8///7/vv8/vr8/vv7/fv8/vr8/vv8/vv8/fv8/fv8/fv8/vv8/vv8/vv8/vv7/fr7/fv8/vr8/vv8/fv8/fv8/vr8/vr7/vv7/vr7/vr8/fv8/vv8/fv8/vr8/vr8/vv8/vv8/vv7/fv7/fv8/vv8/fr8/vr8/fv8/vv8/vv8/vv8/vv7/fv7/fv8/fv8/vv8/vv6/Pv7/fv7/fv8/fv8/vv7/fv7/fv8/vv7/vr8/vv8/vv8/vv8/vv8/fv8//v8/vr8/vv8/fv8/fv8/vr8/vv8/fv8/vr8/vv8/vv7/vr7/vr8/vv8/vv8/vv8/vv8/vr8/vv8/vr8/vr7/vv7/fr8/vv8/fv8/vv8/vv8/vv8/vv8/vv8/vv8/vv8/fv8/vr8/fv8/vv7/fr///z8/fv7/vv8/fr8/vv7/vr8/vr8/fv///802YMbAAAA+HRSTlMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAARI3Z5e+2u34/v337Nm9lmc3EQEBEkeMx+v8++vGi0YSAQIld8n29sl2AgEkhd7ehAERbm0QOLe2AQhm4+JlBxDx6eTo+ooEFJ/10aJyUCojIig2TXGg0fWhFgpxFqX+jkUVAwIVQ43YqAiB99VxHx5w0/6A+IYBHYXq/UMDQjjj/KQdo+Ch9vuSEA+Q+vwMj9kPxx7FJkGGDbfI/nIgjvVFFgmCpeFpAmPbGQwCGiAhFMU63EgBMLomrZH5gwvySJD71ua+ZMaxpBihAqh5DqH00HFNNQQ3tnb1AUUBZrH+/YQAAAABYktHRPw8DqN/AAAAB3RJTUUH5gYcAgUBkLJfBQAABJFJREFUWMNjYMAGGCWlpGVk5eQVFJWUVVTV1DU0tbR1mBiIBMy6evoGhkbGP4Dg549fIOqHiamZuYWlFSMR2pmsbWzt7H9gAQ6OTjbOLAS0s7q4urkr/cABlDw8Xb3w+YSN0dtH/gdeoObrx8qO0/U6/gEmPwgAk0DpIByOYAkOCSWkHQTCwiOwuoE10hw97EyiomNCY6Pi0ITt4yNhbmBMgGnnYElMUkZWlZySmpYunZGZlZ2Tm5dfUIgsp1xUzM4J1l9SCtXPxVRWXoGkQr6yqrqGlRsWOLV19Q2NSOYrNZUx8QD1N7e0wtyvnYok3dbegR7hTLWdXd09CDVFfoxA/b19P6DSEQYI81X7OyZgCWdevomTJsMVTYmPAOuHGMDEH4IIP8Op03BEE9O06WaIkAwH6wcbwMQ6YyZMfNbsDhacCYWdZc5cY5jKefMX/IAawOgdCBNduGgxK76kzrhk6TKYWkg2AwUgs89yWOgvWkEgtwisWAl3A8wARptVMDNna7MyEABMq1N/oRrAJDgJJrKmg1WIkAFcLGvXoRmw3h3KNqrHHX5InmDcEI1sAC+jLYy9sZaoUotx02ZkA5j0tkCZ3R3E6W/ubUU2gFUfmoa2bmMmwgOQ9ItsgIA5lLVqO8EYwKL/B4MeLHXuECbCBxj6fzBIQzPIzl285Oj/wSADLQULdhN2ABb9PxhkoYxUwnHIuGcvhv4fDPtC94NA6AFmQgYwHjx0OGw/OmA40gEBRwk74NjxEx0YgIiYGwW0Bx1YwMlTIgQyFtNRqNIjDPsxQczpMwL4DWBiPgBNf/sYfmCCs+fOE0hVTLWwmlAW04CfKWdYCaVKpt0FEMUmMhgG/Da7wE4wY/Pu2glRPVkaw4CLlwjmKgYm4R1Q1WZ6aAb0XJ7DSrhkZN0Oq4rMBVANmJVUJiBKUD8787atEPX2+qwoBsRdWUxEucbA1NEN1bBFjwnZgKvXrhNTMzDVboTpsGXkRTbgxk1WMcL62VnqjaAa3NcDLUT2wulOJi5C+oVYO9ZAlf+aJIhmwI+5kQQrF1bt2bDKfJUNqPWOYoDxrRUC+PWzrFgEa44t92FmRTfgx+1bq/GGI+viRQthagO9wd0HMPvOXbgb5nYy4nQEO0vH7FkwlTNnQLIMiH0v+z6imfdgeg2OxMA0baohXJl9CD/ErcDAfHiCKSIe0dA0cusUx9LUYprQ0a8KV6RsEAH16w/lR48F2JginyACQqm7q/MpM1rgOXe0tyF1ZVLhzbE4WT1WCQYJprJnSI0v5VUN9XXwypKbtaa6qlIeqbFdUV4GTzHPX4BzH6dA8UuU5v6r1/lv3r7LzsrMkE5PS01JRpZTTkpk4YC57T2sK8caGY/e4YiLig2NiY5aiCZsb449vbFHhIf9+kEYhIYE42jOMul8+Ei40xXgj7sPy84U6aOGX7+8jzcjG56kyhSU6Ymn4+nu5upCKLsBu76ftnzGpt3eztbGmqgS54vUV/PTRpDQ+AXsf4OyiJGhgb6eLjMR2iFmfNPW+q6hLq+qoqykqCAvJysjLSWJvesOAKgmngnLY2fZAAAAJXRFWHRkYXRlOmNyZWF0ZQAyMDIyLTA2LTI4VDAyOjA1OjAxKzAwOjAwOD3eUgAAACV0RVh0ZGF0ZTptb2RpZnkAMjAyMi0wNi0yOFQwMjowNTowMSswMDowMElgZu4AAAAASUVORK5CYII="));
    }else{
        in.loadFromData(QByteArray::fromBase64("iVBORw0KGgoAAAANSUhEUgAAAgAAAAIACAYAAAD0eNT6AAAAAXNSR0IArs4c6QAAIABJREFUeF7s3QnYb1PZP/Dvvdb+PeeIMqVQIeotvL2lEinxmpUpQ8lUNFBvaZBKKTI30b96CyW95gqRCEWJDhKaDA1kioPM0znPXmvd/2uf8+A4nnOe37CHtfb+/q7LZTh73eu+P2s/9v3s3x4E/FCAArELCIDFgelL9eCXUujEX2YpQJc0BnP+PagsBeA5BjoGYEwn/m5gJv5Z5vz3+f5SALOe/ktnKXTOvwtkVoA89WdGZDYQnvqzYpsQ8IhAZgp0ZvH3HPlMAPcC8LGjMj8KdF2g+B8LPxSgQHMCPWD6izK4FRS6okJWEKMrBJUVLbCCAi8AsAQA21yKA89cHPzvVYSZCjPTyNzmIISiUQhz/tnBzgRmF83CQwNH5wAKUKAUATYApTAyCAUWKrBUhmxVhawmRl9WHOShYQUUfweWB2A67PcQoH+FmBs16I0CvdHD3giM/wNA3mEXlk6BygXYAFROzAk6JPDCDNlqYc6BPqwaVFYzwGoAXtghg7JKdQLc7IEbreBGDTKnOXBwNwJ4oKxJGIcCXRZgA9Dl1WftwwrYHnr/6YG1xITXQ4uDvKwKoPgOnp/qBe4B9EYIbkQwv7eQK8Yxfh2AUP3UnIEC7RFgA9CetWQl1Qm8xMKuJUbeoKprAfL64mK76qZj5CEEHgnA76zgcg16hYe/AsB9Q8ThEAp0RoANQGeWmoX2KbBYhmzNAKylgrUMsBaA5focy80iEhDg7ypyhQZcboErcuR/4t0JES0QU2lcgA1A40vABBoWmJYhWxsGG6rqBoC8AUCv4Zw4fTUCjwN6lcxpCvRyD38pgPurmYpRKRC/ABuA+NeIGZYrUHx//zoP3UAFGxrgTQAWKXcKRktEIAB6par83ELOy5FfA6B4LgI/FOiEABuATixz14scW81AN1LR4oC/3tyH6vBDgWcJ3A2RCxDCeR7+Qt5twD2k7QJsANq+wt2sz2TI3gSDbVR1G0BW7iYDqx5BwAN6xcTZgZ/nyK/l2YERNDk0SgE2AFEuC5MaQmARC7sxDLaGypYAlhkiBodQYEECMyF6PgJ+PnF24EFSUSB1ATYAqa9gt/NfysJuEUS2McCmvDWv2ztDjdX7AFxsVE7xyM8E8HCNc3MqCpQmwAagNEoGqklgcYveDkF0JwO8JbFn5NdExGlqFJgFkXMQwike/jwA4zXOzakoMJIAG4CR+Di4JoGehd08iOxqgOL0/rSa5uU0FBhE4AGIni5BTnFwl/CagUHouG0TAmwAmlDnnH0J9NBbO5iwK1TeCWDpvgZxIwrEIXCHCE4tmoEc+R/iSIlZUOCZAmwAuEdEJjBtFQO/i4juAsjLIkuO6VBgYAEBrg+KkwOyU4FZ/xw4AAdQoCIBNgAVwTLsQALTLOwOEOwFSPFgHn4o0FIBvQyK73j403m9QEuXOKGy2AAktFjtS3X6Splxe6liD962177VZUULFbhbBMe64I4GcCetKNCEABuAJtS7PadY2M2CyIcM8FYAptscrL7jAg4iZ0rQbzm44t0E/FCgNgE2ALVRd36ipQ2yPUS0OM3PJ/N1fncgwPwCivAnUfstj/xkAI9TiAJVC7ABqFq44/F76L02GOwN1eJK/ukd52D5FOhH4AERfN+F7NvArJv7GcBtKDCMABuAYdQ4ZkqBDNkGXvAZA2w85cbcgAIUmEwgBODnVlF8PXABnyvAnaRsATYAZYt2O56xsNtA8BlA1uw2BaunQHkCAvxNVQ73yE8C4MqLzEhdFmAD0OXVL6/2MYtece/+pxR4RXlhGYkCFHimgN4MNYd55CcAyKlDgVEE2ACMosexixlke4rg4wBeRA4KUKAuAb1lohH4ARuBuszbNw8bgPataR0VLZ6ZbB9VfBjAknVMyDkoQIHJBOQ2VRwWkB/PBwtxDxlUgA3AoGLd3v45BtlHRPBpHvi7vSOw+tgE5HZVHBGQHwdgdmzZMZ84BdgAxLkusWU1ZtB7v4juD2DZ2JJjPhSgwFMC/1KVohH4HoBZdKHAwgTYAHD/WJhAcVX/LhAcCMhLSUUBCiQjcKeqfCkgP5aNQDJrVnuibABqJ09jQgu7rYgcrMBqaWTMLClAgUkE7oDqpz38KdShwPwCbAC4TzxDIEO2kYoexvv4uWNQoE0CerlR89Ec+VVtqoq1jCbABmA0vxaNnvYyEX+UAbZoUVEshQIUeFpAIXKiD/l+fAMhd4tCgA0A94PnZibbXxUfAzBGDgpQoPUCj6ni8AD3NV4f0Pq1XmiBbAC6u/7Fa3l3g8gRvLK/uzsBK++yQPEwIXzKw/+4ywpdrp0NQAdXv4feG4KEbwCyVgfLZ8kUoMAzBPQ3Rs3HcuTXEqZbAmwAurXey1rTOwKqu/Hrn24tPKulwBQCAaLf98EXz/q4m1rdEGAD0I11zgyyj4ngCwCe242SWSUFKDCEwMOqODjAHQXADzGeQxISYAOQ0GINk2oPvdd68d8TmDWGGc8xFKBA9wQU4epMsz3GMf6n7lXfnYrZALR3rRfJTPZFVXwCgG1vmayMAhSoSCAXweEuuEP5oqGKhBsOywag4QWoYvoM2QYqeiwgq1QRnzEpQIHuCCjCdVbtHjny33Wn6m5UygagXeu8pDX2q1DZo11lsRoKUKBhAS+Co1xwxXVETzScC6cvSYANQEmQTYexsDtA5JsAXth0LpyfAhRoq4D+Q1Te6+B+09YKu1QXG4D0V3t5kezbBtg6/VJYAQUokICAQvQ7PvjPAHgkgXyZ4gIE2AAkvGtY2LdD5LsAlk64DKZOAQokKSC3ieoHHNwFSabPpPkugET3gUWtsV+HyvsSzZ9pU4ACbREQ/YEPvrjb6IG2lNSVOngGILGV7qG3poqerMDLE0ud6VKAAq0VkNtFdUcHN6O1JbawMDYA6SyqMcj2E8GBALJ00mamFKBARwScKvYPcF8GoB2pOeky2QCksXwrWrEnArJuGukySwpQoKsCAbhA1e0K4N6uGqRSNxuAyFfKwu4EkW8DWDzyVJkeBShAgScF7hTFzg7u1ySJV4ANQLxr8xxret+ZeHNfvFkyMwpQgAKTCwRVHBTgDgYQiBSfABuA+NYEwLSXGcnPFJhXRZkek6IABSjQp0AAfqXqdgZwV59DuFlNAmwAaoLudxoLuzVE/o+n/PsV43YUoEACAveIYlcHd2ECuXYmRTYA8Sy1zUx2iCo+DfD5DPEsCzOhAAVKElARHDHxPgFXUkyGGUGADcAIeCUOXUYkO80AG5QYk6EoQAEKRCigv/XqdwRwR4TJdSolNgANL3eG7I0q+DGAFzWcCqenAAUoUJdA8ZXA2/ngoLq4J5+HDUCD/ga9D4vokQB6DabBqSlAAQo0ITAbqu/z8Cc1MTnn5HfNTe0DY9b0vstb/Jri57wUoEAsAiI4zAW3P58eWP+K8AxA/eZLW7E/4VP96ofnjBSgQJwCAThz4umBj8eZYTuzYgNQ67pO+w8r7lxAXlbrtJyMAhSgQOQCinBN0LAVgH9Fnmpr0mMDUNNSZsjWV8GZAJasaUpOQwEKUCA1gbuMylY58t+nlniK+bIBqGHVLHq7Q/QYXuxXAzanoAAFUhd4Aqrv9vDF3VH8VCjABqBC3OKBPpnJDlXFftVOw+gUoAAFWiWgqjhg4j0CrSospmLYAFS3GouIZCcYYPvqpmBkClCAAi0WEDnVh3wPALNaXGVjpbEBqIZ+GSv2Z4C8oZrwjNpxgQcU4TaBPBwgjwJ4zIgWf39UII+GgEcBeUxQ/D089d8F8lg+Z/vxOf9t4i8FsAiA6XP/Pm2RHsKcf1Zo8dfEfy/+zEzXOdvoUmJ0+aCynIEuB8hyAJYFkHV8XVh+JQJ6pVe/JYB7Kwnf0aCZyQ5kA1D+4i+bSXaRAquVH5oROyKggNwBhJshuEmD3CTQmwzMTTnymwA8EKFD8f+SZXroLafQ5RRS/H15MbpcUHmRBV6hwMvZJES4cgmkJMBfnbqN+PjgcharOPgXX7GwASjH88koL84ku3jif3TlRma0tgnMFuCfHrjJCm4Kcw7y4SYPexMw/k8As9tWcHER7BjG/sPDry5GVvOK1S2w2sTPC5+G2cIFL7ckudWr2QiY/Y9y43Yr2pMH/6JqNgClrf30lazkFwPy0tJCMlBbBGYDerWI/FaDzvDwV0/8JlOcfufn6cZgNTGyukJWg4bX82eJu8YkAjOtmo3HMf4X6gwuMO/Bnw3A4H4LGDHtZVbCxYC+pLSQDJSywD0BmCGK3xpghoMrDvht/I2+6jVa3sKuC4M3q+q6AvMqAKbqSRk/eoH7jcpmOfKros80ogTnP/izAShlccZWtRIuAlBcCMVP9wRUEa4TkRkI+K1HNoOnKCvbCRa3sOuIkXVV9c0TF9lOq2w2Bo5Z4BFRbOXgfh1zkrHkNtnBnw3AiKszhrFXeQm/BPCCEUNxeDoCjwXgSiuYc8B3cFcAeDCd9FuV6bQM2esDsK4KNjDA+nzYVqvWd6piZkF1ew9/7lQbdvnPF3TwZwMwwl7RQ++1QfRCAEuPEIZD0xC4H6I/RcDpHv4XAMbTSLtzWT7Pwm4GY7aE6lsBLNU5ge4VnEN1Fw//o+6VPnXFCzv4swGY2m/SLXrorRVEzwewxJAhOCx+gXsgepYEOcPBXQzAxZ8yM5xHwGbI3gyDLaHYinfmtHrfCFD5gEd+XKurHLC4qQ7+bAAGBC02z5AVpxuLU07PHWI4h8QtcCdEfyJBTndwlwLwcafL7PoXGHulQdhSRLcC5I0AbP9juWUCAqoq+wTkRyWQa+Up9nPwZwMw4DJkyDZQwTkAnjPgUG4erYDcJqJnIKD4TX8GAN6aF+1alZbY8w1624uE3fm0ztJMowikigMD3BejSKahJPo9+LMBGGCBMmSbqeAnE49MHWAkN41PQG8SkTOK3/R5K1F8q1NvRmOrZibsropdJx5nXO/0nK10AREc5II7oPTACQQc5ODPBqDPBbWwW0GkeDXlWJ9DuFl8Ak9A9GQTzHdy5NfElx4zaljAFhcQBpHdDVA8d54/6w0vyCjTq2KfAHfkKDFSGzvowZ8NQB8rbGF3gMjJvL2oD6woN5FbVfXbAe57AO6PMkUmFZvA0ga9nSB+d4FZI7bkmE+fAirv98iLn/vWf4Y5+LMBmGK3sLA7Q+T/eMFQej8/Afi1Uf2Gh/8pL+ZLb/1iybiH3quDCe+Fyu4AFoslL+bRl0CA6s4e/rS+tk50o2EP/mwAFrLgFr09IPpdPno0qZ+Kx4vT/DbYb45j/M9JZc5kYxdYwiDbUwR7A1g+9mSZ31MCxXMCtvXwP2ujySgHfzYAC9gjLHrvg+ixfFlSKj8yeouqPHmaP8ZX5aYCyTynFuhZ2J1UdJ+JdxNMPYJbNC0wSxRvdXC/ajqRMucf9eDPBmCS1bCw20DkdJ72L3NXrSZWAH41cZq/uDWT9+xXw8yoCxDIkG3iBZ80wMZEil7gUaOyYY78d9Fn2keCZRz82QDMB108OUwFxaNep/exBtykGYFZED1h4jQ/XwnazBpw1nkExjD2X97oPlB9Fy8WjnrXuN+qWT/1rwfLOvizAXjmD/HqXkLx9Lclo96Fu5uch+j/+eAPBHB7dxlYecQCL8pM9lFV/A8fFhbtKs30atdN9Y2dZR782QA8vY++2Ep2OYAXR7vbdjixAJytaj4LjF/fYQaWno7ActbYL0DlfXOeHs5PZAJyq9d83dR+kSj74M8GYO5uuaQRc6nArB7ZXsp0oJeKymcmHtFLDwokJjDtZdaEg6H6Tl5QHNfSCfA3p65oAu6JK7PJs6ni4M8GAJhuxf4CkDensBN0JUdF+LOofLatt+50ZR1Z51yBHnprONHDDbApTWIS0Ku8+vUAPBFTVvPnUtXBv+sNgBXJzjDA1jEvfrdyk1uh4Qse/iQAoVu1s9q2C2TI1lfRwwFZu+21JlOfyI98yHeM9SVgVR78O90AWGOPKd4hncyO2u5E/60qhwXk3wYwu92lsrquCxS3GovIoQqs1nWLGOoXwRddcMXFxVF9qj74d7YBMMj2EcFXo1rtbibzmAiOcsF9BcDD3SRg1R0VsBNPGz0CwFIdNYinbNUdPfwPY0mojoN/JxsAC/tWiBQPjjGxLHYH8wjFkxZ98MV7u2d2sH6WTIEnBZ5vTe+rUH03SRoVeMKorBfD68HrOvh3sAEYW9VKuALA8xrd1To8uQA3QPFeB1fcdskPBSgw517BbD0IvqPAqgRpTOAur25NAP9qKoM6D/5dawCWsmKvBORlTS1ux+d1IviyC+4gfs/f8T2B5S9IYMwg21cEnwOwCJnqF1CEa4KG4vbAx+ueve6Df5cagEwkO98AG9a9qJwPUIRrrdo9cuR/oAcFKDCVwPSVRdz/GmCzqbbkn5cvEIAzVN0Odd4Z0MTBvzMNgDX2m1D5cPm7CiNOITBbFV8MmHORn6MWBSjQv4CF3QEiX+frh/s3K2tLERzqgtu/rHgLi9PUwb8TDYBBb08RPbqOheQc8wroDK/2vcD4jXShAAWGFnieNfZQqBTvF5Cho3Dg4AKqu3j4kwcf2P+IJg/+rW8AigtrJt7u1+t/SbjliAKPqcpnA/Jv8WE+I0pyOAUmBDJkG6ngBwBeRJTaBGYblfVz5MWF46V/mj74t7wBmL6SFXcVgOeXvnIMOKlAAH6pmr0fmHULiShAgdIFlhLJjjHA9qVHZsAFCdzt1b0ewB1lEsVw8G9zAzBmxV4GSHFLBz/VCzwIlX088u9XPxVnoEC3BSx674HoNwA8t9sSdVWvv/Xq1y/rOqZYDv6tbQAyk/0/Vexd1+7R5XkCcI6q2xPAXV12YO0UqFdg+spW8pMAeWO983ZzNhEc7oL77KjVx3Twb2UDYGG3hcgZoy4Ux08p4FWx38QV/lNuzA0oQIHSBaxB9jkRfH7Os4T4qVJARbGZg7tw2EliO/i3sAEoumJ3DYDFh10kjutL4B5R7OjgftXX1tyIAhSoTKCH3lpBQnE2gA85q0x5TuB7vLrXDHO2M8aDf9sagDEjZobAvK7afaDr0fUKr764CKmxx2V2fQVYPwUmEVhs4nkn76FOdQIB+JWq22iQO5xiPfi3qgHgw36q2+mfiiz6bR/8xwGM1zAbp6AABQYUMOjtJXMvEOStzwPa9bu5Kg4McMWLzKb8xHzwb00DYGG3h8iPp1wNbjCswBNQ3cvDnzBsAI6jAAXqEciQvVkFpwN4YT0zdm6WIIoNHdyvF1Z57Af/ljQA01ax4ovv/fmGv0p+DvVmo2bbHPkfKwnPoBSgQBUCL7Ziz+St0FXQzolZvDnw1QDunWyGFA7+bWgAiu/9rxCYNSpb5g4HDsC5qm4XAA92mIGlUyBVgWnW9I6B6rtTLSDmvANwgarbfP6XBqVy8E++AchMdoQqPh3zTpJobmHiJT4H1/lGrEStmDYFohYw6O0tol/jrYLlL9PErdBHPBk5pYN/0g1AhmwdFVwKwJS/rJ2OeL8odnZw53dagcVToEUCGbL1VfAjAMu0qKwYSnGiWM/BzUjt4J9yA/AcK/aPvO+13P1fEa4NOrYtn+VfriujUSASgRWMmLP4lWnZqyG3i+hpqti37MhVx0vy9ZLW2P+FyoeqxulS/AD8QtW9HcBjXaqbtVKgYwKLiGSnGmDrjtXNcicRSK4ByJBtrIIL+G7s8vbnAJyh6nbi/f3lmTISBSIWsNbY70Jl94hzZGo1CKTWACxuJfsLgBfXYNONKUS/74P/AADfjYJZJQUoUAhkJvuSKj5Fje4KJNUAWNM7Aaq7dne5yq1cBEe64D7JK/3LdWU0CqQiYJDtI4Kv8IxqKitWbp7JNAAW9u0QObPc8rsbTRWfD3CHdFeAlVOAAoWAhX03RL7H2wS7tz+k0gAsYyW7jrewlLKDqqp8JCD/31KiMQgFKJC8gIXdAiLFbYKLJF8MC+hbIIkGwJreaVB9Z99VccMFCTiovsfDn0wiClCAAvMKTLxD4BwAS1CmGwLRNwAZss1U8PNuLEelVc6C6js8fPEDzg8FKECBZwmMYexVXkJxl9Vy5Gm/QOwNwCJW7F8AWbn9S1FphY+IYksHd0mlszA4BSjQAoHpL7Xifw3oCi0ohiUsRCDqBiAz2WHFs5a5giMJ/NuobJYjv3qkKBxMAQp0SGDOW1Z/A2D5DhXduVKjbQDGMLa6l3AtgF7nVqW8gv/l1WwMjN9QXkhGogAFuiEw9koroThr+IJu1Nu9KmNtAMSKvRSQN3VvSUqr+C6v2ZuAWf8sLSIDUYACnRKYuCbgVwCW7lThHSk2ygbAovd+iB7bkTWoosyHrJq3jGP8T1UEZ0wKUKA7Aj30XhtEL+LdAe1b8xgbgBdYyW4EsGT7uGupaLYoNuUFf7VYcxIKdEKgh95aQfQXAJ7biYI7UmR0DYA1vROhuktH/MsuM0B1Bw/PJyaWLct4FOi4QIZsXRWcD+A5HadoTflRNQAZsg1V8MvW6NZciKrsFZAfU/O0nI4CFOiIwMT/o38GYHpHSm51mTE1ANaI+aPArN5q8YqKU8WBAe6LFYVnWApQgAJzBCzs5hA5C8AYSdIWiKYBMOjtKaJHp83ZUPaiR/vgP9jQ7JyWAhTomICF3QkifKR44useSwPwPCvZ33m/6eB7UwDOVHU7AAiDj+YIClCAAsMJGGRfEAHPOg7HF8WoKBqAzGSHq+IzUYgklYRe4tVvCmB2UmkzWQpQoBUCvGg77WWMoQFYceK2P15UMsC+pAh/DBrWA/DQAMO4KQUoQIEyBcas2F8Csm6ZQRmrHoHGGwC+6neYhdZbvPp1ANw1zGiOoQAFKFCiwNJW7BWAvKzEmAxVg0CjDUCG7I0qmFFDnW2a4l6v9k3A7OKaCX4oQAEKRCAw7T+s+Cv4ALcIlmKAFBptAKzYywFZe4B8u77pbKOybo78qq5DsH4KUCAugQzZ+iq4kC9wi2tdFpZNYw2Ahd0RIqemQ9V8pnzQT/NrwAwoQIEFC1j03gPR42mUhkBTDcA0K72/ArpiGkwRZClysg85H5EcwVIwBQpQYMECmckOVcVnaRS/QCMNgEHvIyL6jfh54shQgBucujUBPBZHRsyCAhSgwAIFRCQ7ywBb0ShugSYagOlWspsBLBc3TTTZPebVvAEYvz6ajJgIBShAgYULLGmldy3P8sa9m9TeABj0PiaiR8XNElF2qrt6+JMiyoipUIACFJhSoIfe2kH0N7wocEqqxjaouwFYZOK3/2UbqziliUWP9cHvmVLKzJUCFKDAkwIG2T4i+CpF4hSotQHgztD/TqAI1wYNxcN+ZvU/iltSgAIUiEtAJPupAbaMKytmUwjU2QAsOvHb/wtIP6XAQ17t64DZN025JTegAAUoELfAUhPXA6wQd5rdy662BsAg+5QIvtQ94iEqVt3Ow585xEgOoQAFKBCdwMRTX4vrAbLokutwQnU1AItZyf4J4Pkdtu6rdBEc5YL7RF8bcyMKUIACiQgYZPuK4MuJpNuJNGtpAAyy/URwWCdERypSL/fqizf85SOF4WAKUIAC8QkUzwc4xwBviy+1bmZURwPwXCvZLQCW6iZx31Xf59WtAeD2vkdwQwpQgAJpCSw9cT3AS9JKu53ZVt4AGGSfFMFX2slXYlWqb/XwPy8xIkNRgAIUiE4gQ7bxxEuDosutawlV3QBkVno3A8pub2F7lugPfPC7d23nY70UoEA3Bayxx0Flj25WH0/VlTYAFnYniJwcT7lRZnKvV/dKAPdHmR2TogAFKFC+wBJWsusALF9+aEbsV6DSBsCI+b3AvK7fZDq5neouHp5NUicXn0VToLsCFnYriJzdXYHmK6+sAciQraeCXzdfYrwZBOBCVbdpvBkyMwpQgALVCVjTOwWq76puBkZemEBlDQAf/zjljve41+w/gVnF8xH4oQAFKNBFgedbyYo3nS7TxeKbrrmiBmDaf1jxN9b8qOGmLQeaXxWfCnC8O2IgNW5MAQq0TcDCvhMip7WtrhTqqaQBsMZ+Byp7pQDQRI6K8IegYU0Aron5OScFKECBmAREsp8YYJuYcupCLlU0AEtbyYqH2SzSBcAhagxGZa0c+e+HGMshFKAABdoosNzEVwFLtLG4WGsqvQEwyPYXwcGxFtx0XiL4ugvu403nwfkpQAEKxCRg0XsPRI+PKae251J2A9Czkt0GYNm2ww1Xn9zmNV8dwKPDjecoClCAAu0UyEx2oCoOaGd1cVZVagNgYbeDyOlxlhpBVqpbevifRZAJU6AABSgQjQAP/s0sRakNgEh2gQE2aaaUyGcV+bEP+Tsiz5LpUYACFKhVgAf/WrmfMVmJDcD0lay4m3nr36SL+aBXtyqAmc0tNWemAAUoEJcAD/7NrkdpDUBmskNU8blmy4lzdlXZKyA/Js7smBUFKECB+gV48K/ffP4Zy2oAMivZrXyxw7MXVIC/OnXFhX+++eVmBhSgAAWaF+DBv/k1KDIopQGwsFtD5Kw4SoosC9V3eXg+5SqyZWE6FKBAMwI8+DfjPtmspTQAItnPDPC2eMqKIxNF+HPQ8GoAGkdGzIICFKBAcwI8+DdnX1UD8BIr2S0ATFylRZCN6jYenq+7jGApmAIFKNCsAA/+zfpX0gAYZAeI4MD4Sms6I73Kq39D01lwfgpQgAJNC/Dg3/QKTD7/qF8BGCu9WwB9SZzlNZeVKDZ1cBc2lwFnpgAFKNC8AA/+za/BgjIYqQHIkG2iggviLa+pzPRSr/4tTc3OeSlAAQrEIMCDfwyrsOAcRmoArLHfh8rucZdYf3aiWM/B/ab+mTkjBShAgTgEePCPYx0WlsUoDcCYlexuAHx94zzCAbhQ1W0a/9IzQwpQgALVCPDgX41r2VGHbgB47//kS2FU1sqR/67shWI8ClCAAikI8OCfwirNzXH4BsD0ToXqjumUWn2mAfipqtuSsoiUAAAgAElEQVS6+pk4AwUoQIH4BHjwj29NqvgK4DlWsnsALJpWuZVmq1bNa8Yx/qdKZ2FwClCAAhEK8OAf4aJMkdJQZwAs7Dshwsfbzosr8kMfcp4RSe9ngBlTgAIjCvDgPyJgQ8OHagBEsrMMwFPdTy+a92pXB2b/taF15LQUoAAFGhHgwb8R9lImHaYBWHzi6v9ppWTQhiAiJ/mQ79qGUlgDBShAgX4FePDvVyrO7QZuACx674Ho8XGW00xWRmXtHPmVzczOWSlAAQrUL8CDf/3mZc84cAMgkp1vAN7nPrESinBt0PDasheG8ShAAQrEKsCDf6wrM1hegzYAS1jJ7gWQDTZNi7dW+YBH/t0WV8jSKEABCjwlwIN/e3aGgRoAXv3/rIV/2KtbHsBj7dklWAkFKECByQV48G/XnjFYA2B6J0CVF7s9uQ+IfssH/5F27RKshgIUoMCzBXjwb99eMUgDYCau/n9++xiGq8iq+c9xjF833GiOogAFKJCGAA/+aazToFn23QBkyN6oghmDTtDe7fU3Xv167a2PlVGAAhQAePBv717QfwNgskNU8bn2UgxYmepOHv7UAUdxcwpQgALJCPDgn8xSDZVo3w2AEXOtwLxmqFnaN+ger+4lAMbbVxorogAFKMDf/LuwD/TbALzYSnZ7F0D6qVEER7jg9utnW25DAQpQIDUB/uaf2ooNl29fDYBB7wMiesxwU7RuVPCarQLMuqV1lbEgClCg8wI8+HdnF+irARDJzjbAVt1hWXClAThP1b2NFhSgAAXaJsCDf9tWdOH19NMATLeS3QfgOd2iWUC1qlt6+J/RggIUoECbBHjwb9Nq9lfLlA1AhmxjFVzYX7i2byW3ec1fCiC0vVLWRwEKdEeAB//urPW8lU7dAPD2v6e8itsgA9xh3dxVWDUFKNBGAR7827iq/dU0ZQNgxf4GkHX7C9furby6FQHc1u4qWR0FKNAVAR78u7LSk9c5VQNQfP//IIBp3WYC+Nrfru8BrJ8C7RLgwb9d6zlMNQttADJk66ng18MEbtsYVRwY4L7YtrpYDwUo0D0BHvy7t+aTVbzQBsAg+7wIDiIVYFTWyJH/gRYUoAAFUhbgwT/l1Ss394U2ACLZLw2wYblTphhNbvWar5Ri5syZAhSgwJMCPPhzX5hXYGENQG/i+3/e/y/6TR/83tx1KEABCqQqwIN/qitXXd4LbAD4+t+n0UWxoYO7uLplYGQKUIAC1Qnw4F+dbcqRF9gAGGSfLl56k3JxJeX+oFe3DABXUjyGoQAFKFCbAA/+tVEnN9ECGwCR7FwDvDW5ispOWORkH/Jdyg7LeBSgAAWqFuDBv2rhtOMvqAEwVrIHADwv7fJKyF71HR7+xyVEYggKUIACtQnw4F8bdbITLaABGFvVSrg+2arKS3zcq3s+gEfKC8lIFKAABaoV4MG/Wt+2RJ+0AbCwO0PkpLYUOWwdAThf1W0+7HiOowAFKFC3AA/+dYunO9+kDUBmsiNV8fF0yyonc1X5YEB+dDnRGIUCFKBAtQI8+Ffr27bok58BEPtrQNZrW7ED1qNe3YsB3DngOG5OAQpQoHYBHvxrJ09+wskaAJl4AFDHLwDUq7z6NyS/wiyAAhRovQAP/q1f4koKnKQBmPZyK/5vlcyWUFBV7B/gDk0oZaZKAQp0UIAH/w4uekklP6sBsLA7QuTUkuInG8aovD5HfnWyBTBxClCg9QI8+Ld+iSst8FkNQGayL6ti30pnjT/4E15d8RUIn/4X/1oxQwp0UoAH/04ue6lFP6sBEMkuMsAGpc6SXDD9rVf/5uTSZsIUoEAnBHjw78QyV17ks78CkOx+AEtWPnPEE4jgSBfcPhGnyNQoQIGOCvDg39GFr6Ds+RqA6StbcTdVME9aIVXf6eF/lFbSzJYCFGi7AA/+bV/heut7RgNgYd8OkTPrTSG+2by6lQDcGl9mzIgCFOiqAA/+XV356up+RgPAVwDPgb7bq1u2OnJGpgAFKDCYAA/+g3lx6/4EnnkGwNjjoLJHf0PbuVUAfqrqtm5ndayKAhRITYAH/9RWLJ18n9kAiL0UkE5f/a6KzwW4w9JZQmZKAQq0VYAH/7aubBx1zdcAZPcAWCaO1JrJQhQbObiLmpmds1KAAhSYK8CDP/eEqgXmbQCWsJI9UPWEkccvXgC0BICHI8+T6VGAAi0W4MG/xYsbUWlPNQA99N4QRK+MKLfaUxHgBqdutdon5oQUoAAFJgR48OeuUJfAUw2Ahd0FIifWNXGU84j+wAe/e5S5MSkKUKD1Ajz4t36JoyrwqQYgM9lBqvh8VNnVnIyqfDAgP7rmaTkdBShAAX7nz32gdoGnzwCY3mlQfWftGUQ0oVF5bY782ohSYioUoEAHBPibfwcWOcISn2oAjJhrBGaNCHOsKyW+AbAuac5DAQo8JcCDP3eGpgSePgMg2aMAFm0qkebn1cu8+nWbz4MZUIACXRHgwb8rKx1nnc96G2CcaTIrClCAAhSgAAXKFGADUKYmY1GAAhSgAAUSEWADkMhCMU0KUIACFKBAmQJsAMrUZCwKUIACFKBAIgJsABJZKKZJAQpQgAIUKFOADUCZmoxFAQpQgAIUSESADUAiC8U0KUABClCAAmUKsAEoU5OxKEABClCAAokIsAFIZKGYJgUoQAEKUKBMATYAZWoyFgUoQAEKUCARATYAiSwU06QABShAAQqUKcAGoExNxqIABShAAQokIsAGIJGFYpoUoAAFKECBMgXYAJSpyVgUoAAFKECBRATYACSyUEyTAhSgAAUoUKYAG4AyNRmLAhSgAAUokIgAG4BEFoppUoACFKAABcoUYANQpiZjUYACFKAABRIRYAOQyEIxTQpQgAIUoECZAmwAytRkLApQgAIUoEAiAmwAElkopkkBClCAAhQoU4ANQJmajEUBClCAAhRIRIANQCILxTQpQAEKUIACZQqwAShTk7EoQAEKUIACiQiwAUhkoZgmBShAAQpQoEwBNgBlajIWBShAAQpQIBEBNgCJLBTTpAAFKEABCpQpwAagTE3GogAFKEABCiQiwAYgkYVimhSgAAUoQIEyBdgAlKnJWBSgAAUoQIFEBNgAJLJQTJMCFKAABShQpgAbgDI1GYsCFKAABSiQiAAbgEQWimlSgAIUoAAFyhRgA1CmJmNRgAIUoAAFEhFgA5DIQjFNClCAAhSgQJkCbADK1GQsClCAAhSgQCICbAASWSimSQEKUIACFChTgA1AmZqMRQEKUIACFEhEgA1AIgvFNClAAQpQgAJlCrABKFOTsShAAQpQgAKJCLABSGShmCYFKEABClCgTAE2AGVqMhYFKEABClAgEQE2AIksFNOkAAUoQAEKlCnABqBMTcaiAAUoQAEKJCLABiCRhWKaFKAABShAgTIF2ACUqclYFKAABShAgUQE2AAkslBMkwIUoAAFKFCmABuAMjUZiwIUoAAFKJCIABuARBaKaVKAAhSgAAXKFGADUKYmY1GAAhSgAAUSEWADkMhCMU0KUIACFKBAmQJsAMrUZCwKUIACFKBAIgJsABJZKKZJAQpQgAIUKFOADUCZmoxFAQpQgAIUSESADUAiC8U0KUABClCAAmUKsAEoU5OxKEABClCAAokIsAFIZKGYJgUoQAEKUKBMATYAZWoyFgUoQAEKUCARATYAiSwU06QABShAAQqUKcAGoExNxqIABShAAQokIsAGIJGFYpoUoAAFKECBMgXYAJSpyVgUoAAFKECBRATYACSyUEyTAhSgAAUoUKYAG4AyNRmLAhSgAAUokIiAWMk0kVyZJgXmCoh+0wf/UQDcd7lPUIACAwlYsZcC8uaBBrVr48e8usXm/K+UDUC7Vrbt1ajigAB3UNvrZH0UoEAlApmV7GEAi1QSPYGginBt0PBaNgAJLBZTfEogqMqHA/Lv0IQCFKDAMAI99NYIotcMM7Y1Y0R+6EO+IxuA1qxo6wsZh+puHv6Hra+UBVKAApUJGPT2EtFO/xIhgoNdcF9gA1DZbsbAJQo8JoptHdyFJcZkKApQoIMC1tjjofKeDpb+dMmqu3r4k9gAdHovSKL4+4zK23LkVyaRLZOkAAWiFsgku16BVaNOsuLkjMpaOfLfsQGoGJrhRxK4w6vZBBi/YaQoHEwBClBgrsDzrGQPFhe/dxnEq1sSQOHAuwC6vCPEWrsAf3XqNgFwW6w5Mi8KUCAtgQzZhir4ZVpZl57tvV7dC56MytsAS/dlwNEE9Pde/eYA/j1aHI6mAAUo8LSAQfZZERzabRO9zKtflw1At/eCKKsPwEWqbhsAj0aZIJOiAAWSFRDJzjbAVskWUEbiot/3wb+XDUAZmIxRmkAAzlB1OwEYLy0oA1GAAhSYELCSzQTwwi6DqOIzAe5LbAC6vBfEVrvosT74DwIIsaXGfChAgVYIrGglu6UVlYxShOq2Hv4nbABGQeTY0gREcJgL7nOlBWQgClCAAvMJWNh3QKTzDxLzmq0CzLqZDQB/RJoWUFX5RED+9aYT4fwUoEC7BTKTfU0Vn2h3lVNW94BXt9S8W/EugCnNuEEFAg6qe3j4EyuIzZAUoAAFniFgxV4GyJu6zBKAi1XdhmwAurwXNF/7E1DdwcOf23wqzIACFOiAQOffAFissQi+4oL7FBuADuzxkZb4oCi2dHCXRZof06IABVom0EPvdUH09y0ra/ByVN/l4U9jAzA4HUeMLnCXVbPZOMb/NHooRqAABSjQn4BB9jkRHNLf1u3dyqv9D2D239kAtHeNI61Mb/La22Teq08jTZRpUYACLROwYn8HyJotK2vQch726pYAoGwABqXj9kMLKMIfg4ZNAdw9dBAOpAAFKDCcwPJWsju6/gIgQC/x6tefn5B3AQy3U3FUXwJ6qVe/JYCH+tqcG1GAAhQoUcCgt5eIfqfEkEmGEsFRLrhn3QbJBiDJ5Yw/6QCco+reAWBW/NkyQwpQoI0CItnPDbBZG2sbqCbVXTz8yTwDMJAaNx5KQOT/fMjfB8ANNZ6DKEABCowu8FwrWfFW0bHRQ6UdwatZDRi/gQ1A2usYffYi+JoLbt/5LzaJPnEmSAEKtErAwu4AkR+1qqjhiikuAFxysnet8CuA4UA5ahKB+d80RSQKUIACTQlY0zsJqjs3NX8s8wbgPFX3tsnyYQMQyyqlnYeHyp4e+XFpl8HsKUCBlggUT/+7F0Bx61unPwv7xYwNQKd3jVKKn425T5h66hWTpURlEApQgAJDCmTINlDBRUMOb9UwUazj4C7nGYBWLWsUxTwiiq0d3K+iyIZJUIACFABgjf0GVD5CDDw+8QCgnA0A94YyBe41KpvlyK8pMyhjUYACFBhVwErvFkBXHDVO6uMDcJGq22hBdfArgNRXuJH85VavZhNg9t8amZ6TUoACFFiAQA+91wTRawkEqOILAe5gNgDcG0oRUITrJh7t+69SAjIIBShAgRIFDLIDRHBgiSGTDSWK9R3cJWwAkl3CmBLXK7z64naS+2PKirlQgAIUeFLAiLlGYNagCGZPfP+/wKex8isA7iV9CQTgfFW3HYDH+xrAjShAAQrUL7CClezW+qeNccY572J5y8IyYwMQ47rFlpPIqT7k7wYw6ZWksaXLfChAgW4KGGSfFcGh3az+mVUXDi64/dkAcG8YXkD0Wz74vflo3+EJOZICFKhFwFjp/RPQFWqZLfJJRLGJg/sFG4DIFyrW9FRxYID7Yqz5MS8KUIACTwpY2C0gcg5F5ggU9/8vPdXbWPkVAPeWyQSCqnwkIP82eShAAQqkICCSnWuAt6aQa9U5BuCnqm7rqeZhAzCVUPf+PIfqrh7+h90rnRVTgAJpCkxfyYq7CYBJM/9ys1aVPQPyY6eKygZgKqFu/fljotjWwV3YrbJZLQUokLJAZrLDi5fepFxDmbl7dS8BcMdUMdkATCXUnT+/36i8NUd+ZXdKZqUUoEALBMasZLcDeEELahm5BEX4Q9DQ13MQ2ACMzN2KAHd4NZsC49e3ohoWQQEKdEbAwr4LIqd0puApCu3n9r8nQ7AB6PheI8BfnbpNANzWcQqWTwEKJChgxV4CyEIfeJNgWUOnvLDX/84flA3A0MzpD1SEq4OGzQHcm341rIACFOiawBjGVvcS/tK1uhdS77+9uhcCCP2YsAHoR6mF2wTgYlW3DYBHWlgeS6IABTogYI39JlQ+3IFS+ytR5EQf8t362xhgA9CvVIu2C8AZqm5nALNbVBZLoQAFuiWwqJXsTgDP61bZC6lWdcdBbuFmA9C1PUf0uz74vfo9RdQ1HtZLAQqkIWDRez9Ep7zXPY1qSsnSeXXLAHiw32hsAPqVasF2IjjcBffZFpTCEihAgY4L8LW/z9wBAnCBqttskN2CDcAgWuluq6qyT0B+VLolMHMKUIACcwV66K0VRK+gxzwCKrt75D8YxIQNwCBaaW7roPpeD39CmukzawpQgALPFLCmdyJUd6HLUwKzJ67+f2gQEzYAg2ilt+0TUH2Hh/9ZeqkzYwpQgAKTCUx7hRV/HQBLn7kCATh74q6ugUjYAAzEldTGD4piSwd3WVJZM1kKUIACCxGwpncaVN9JpHkEBrz6/8mRbADauRfNtGo2Hcf4n9pZHquiAAW6KDCGsf/yEv4AQLpY/wJqfsyrK96D8PigJmwABhWLfnu9yWtvE2DWzdGnygQpQAEKDCAgkp1tgK0GGNL+TUVO8yF/1zCFsgEYRi3SMYrwx6ChuA1kZqQpMi0KUIACQwn00HtDEOXbSufXU93Gw589DCobgGHUohyjl3r1WwIY6CrQKEthUhSgAAXmExDJLjBA8eIyfp4WeHDi6v/xYVDYAAyjFtmYAJyj6oqLYp6ILDWmQwEKUGBkgQzZW1RwyciB2hZA9Hgf/B7DlsUGYFi5WMaJnOBD/l4ALpaUmAcFKECBMgWs2N8Asm6ZMdsQSxSbOrgLh62FDcCwchGME8GRLrhPAtAI0mEKFKAABUoXyJBtooILSg+cfEC53Wu+0ijvdWEDkOhOoIr9AtwRiabPtClAAQr0JWDF/g6QNfvauEMbqeLAAPfFUUpmAzCKXjNjPVT28si/18z0nJUCFKBAPQIWdmuInFXPbEnNEry64rf/20fJmg3AKHr1j50N1Z08/Jn1T80ZKUABCtQqIEbMHwXmVbXOmsBkAThX1W0xaqpsAEYVrG/8I6LY2sH9qr4pORMFKECBZgQs7I4QObWZ2SOfdYR7/+etjA1A5Os8kd69RmXzHPnVaaTLLClAAQqMJGAzya5T4BUjRWnn4Du9uhXLuPOLDUD0O4jc6tVsAsz+W/SpMkEKUIACJQgY9PYU0aNLCNW6ECI41AW3fxmFsQEoQ7GiGAJc79QVT776V0VTMCwFKECB2ASWtZLdAGCJ2BKLIB/1mq0MzLqljFzYAJShWEkMvcKrfxuA+ysJz6AUoAAFIhSwpvcjqO4QYWqNpxSAC1XdpmUlwgagLMkS4wTgAlW3HYDHSgzLUBSgAAWiFrCwW0DknKiTbDI51e09/BllpcAGoCzJsuLMfbXjbgDyskIyDgUoQIEEBBaz0rsO0BUSyLWJFGd6dYVNaccGNgBNLOOC5hT9Xx/83qM82jGmcpgLBShAgX4FMpMdpYqP9bt917ZTxecD3CFl1s0GoEzNEWKV8VjHEabnUApQgAKNCfTQe30QvRKAaSyJuCd+wqt7CYD7ykyTDUCZmsPFCqqyd0D+v8MN5ygKUIACSQtkRsxVAvOapKuoMnnRo33wHyx7CjYAZYsOFi+H6m4e/rTBhnFrClCAAu0QMMj2FcGX21FNJVWoV/vKKp4FwwagkvXqM6jqdnyuf59W3IwCFGihwPSXWnF/AfCcFhZXSkkBOEfVbVVKsPmCsAGoQrXfmKLH+uD37HdzbkcBClCgTQIi2QUGKB52xs8CBESxvoO7pAogNgBVqA4SU3VLD/+zQYZwWwpQgAKpC1jYnSFyUup1VJm/IlwdNLy+qjnYAFQl23/cu7264nWX9/Y/hFtSgAIUSFpgKSvZjQCWSbqKqpNX3dnDn1LVNGwAqpIdIG4AzlZ12wwwhJtSgAIUSFbAGns8VN6TbAG1JC63e81XLuOtfwtKlw1ALQvZxyQq7/PIj+tjS25CAQpQIFkBC7s5RM5LtoCaElfFvgHuq1VOxwagSt3BYj/q1b4GmH3TYMO4NQUoQIFkBF5iJbsWwNLJZNxMovd7dSsBeKTK6dkAVKk7cGy93KtfF4AfeCgHUIACFIhboGfFXgLIG+NOs/nsVPHZAHd41ZmwAahaeMD4VTzvecAUuDkFKECB0gUykx2pio+XHrh9Af/t1b0UwKNVl8YGoGrhwePnRuWNOfKrBx/KERSgAAXiE7Cw20KktNfYxldheRmp4tMBrpYnI7IBKG/dSoskwN+cuuLez0q//yktYQaiAAUosECBaatY8cUvNIsTaUqBe7y64sr/x6bcsoQN2ACUgFhFiAD8RNVtB0CriM+YFKAABWoQmG7EzBCYNWqYK/kpVPHJAPe1ugphA1CX9BDzqOJzAe6wIYZyCAUoQIHGBayxx0DlA40nkkYCMyd++3+irnTZANQlPdw8QRRvdXAXDDecoyhAAQo0I2Bhd4HIic3Mnt6sqvLxgPzrdWbOBqBO7eHmut9r9npg1j+HG85RFKAABeoWGFvNSvgdgEXrnjnR+e6a+O1/Vp35swGoU3vIuRThD0HDOgBqOzU0ZKocRgEKUGDRTLKrFFiVFP0JqMreAfk3+9u6vK3YAJRnWW0kkRN9yHerdhJGpwAFKDCagDW9k6C682hRujRabvWavwLA7LqrZgNQt/gI8zXVJY6QModSgAIdEjDo7SmiR3eo5NFLVX2Xhz9t9ECDR2ADMLhZkyNyUWzg4C5rMgnOTQEKUGB+gR56awbRSwFMo06/AnqFV9/Yo5HZAPS7TvFsV9wq8gYAt8eTEjOhAAW6LTDt5Vb8bwEs022HwaoXxToO7vLBRpW3NRuA8ixri6QI1wUNxUuDHqhtUk5EAQpQYHKB5azYGYAUb6/jp18BkR/6kO/Y7+ZVbMcGoArVWmLqZV79xgBqvW2kltI4CQUokIrA4kbMJQLz6lQSjiTPWV7dKwHc2mQ+bACa1B9x7onHBW8PIIwYisMpQAEKDCowzYq9AJD1Bh3Y9e1FcIQLbr+mHdgANL0Co84v+h0f/IdGDcPxFKAABQYQMCLZjw2w7QBjuOlcgeKFPy8H8HDTIGwAml6BEuZXxf4B7tASQjEEBShAgSkFrLHfgcpeU27IDZ4loCp7BeTHxEDDBiCGVSgjB5U9PPLjywjFGBSgAAUWJGCQHSCCAyk0uMDEBdzF9RJ+8NHlj2ADUL5pUxEdVLf28Oc1lQDnpQAF2i3AB/2Mtr6i2MjBXTRalPJGswEozzKGSI8blf/OkRcv4eCHAhSgQGkCFnZbiPwYgCktaJcCiZzkQ75rTCWzAYhpNcrJ5d9WzQbjGP9zOeEYhQIU6LpAhmw9FRSvJedT/obbGR6YuO3vnuGGVzOKDUA1rk1HLZqADccx/qemE+H8FKBA2gJjGPsvL+E3ABZPu5IGs1f5gEf+3QYzmHRqNgCxrUh5+dxnVDbMkf+xvJCMRAEKdEtg+kutuOIRv8t1q+4yq9XfevXFk1u1zKhlxGIDUIZivDHuNyob5civjTdFZkYBCsQpMLaqlfALAC+KM78kssqtmjXGMX5djNmyAYhxVcrNqWgCNs6RX1NuWEajAAXaKtBD73VB9HwAz29rjXXUJYLDXXCfrWOuYeZgAzCMWnpjHphoAq5OL3VmTAEK1CkwccHfOQCeW+e87ZtLb/bq/xPAE7HWxgYg1pUpP68HJ5qA35cfmhEpQIE2CFjYLSHyIwDT21BPkzWIYnMHV5xFifbDBiDapakksaIJ2JTPCajElkEpkLSAhd0ZIj8AkCVdSAzJR/Cq334Y2AD0o9SubR4Sxdsc5lzZyw8FKEABGPT+R0S/CUDIMbLAvV7d6gDuHTlSxQHYAFQMHGn4WVDd1cOfHml+TIsCFKhJwCDbXwQH1zRd+6dR3dbD/ySFQtkApLBK1eSoqvhkgDuymvCMSgEKRC4gmcm+qopPRJ5nOumJnOhDvlsqCbMBSGWlqspT9Js++I8BCFVNwbgUoEB0AtYaeyxU9ogus3QTusOrK676fyiVEtgApLJSFeYZgLNU3U4x365SYfkMTYGuCYyJZKcYYLuuFV5hvSqKTR1c8eCkZD5sAJJZqqoT1Su9+i1TuHClagnGp0CLBRYVyX5igI1bXGP9pYl+2wf/P/VPPNqMbABG82vZaL3Ja7Y5MPvvLSuM5VCAApi+kpHxMwVmDWKUKaD/8OpfDeDxMqPWEYsNQB3Kac3xb1Fs5eAuTyttZksBCixIIEO2mQpOBrAUlUoVCKJY18HNKDVqTcFSbgBcAH7FU1mV7CnFbYJ7evgTKonOoBSgQF0CYpB9XgQHADB1TdqVeUTwJRfcZ1KtN9UG4HGo7uDhL7RiLwFknVQXIOq8RY/xwX8UwOyo82RyFKDAZAJLiGQnGeBt5ClfQBGuDRrWBjBefvR6IqbYADwgii3mOeXyYitZ8bpbvrWqkn1Gf+/Vbw/g1krCMygFKFC6QA+9VwcJZwKycunBGbAQeNirfS0w+6aUOVJrAO60ajYdx/hf5kWf+H7rPD7GsrJd8T5R7OzgLqhsBgamAAVKEbCwu0HkaACLlBKQQZ4tMPcMdPJPUk2oASiutOxtDMy6ZbL9MTPZoaqI9r3LLfgZCqo4KMAVjwzlQ4NasKAsoXUCY9bYo6DyodZVFlNBot/ywX8kppSGzSWJBmDiu5bNANyzkEKtFXsRIOsNi8FxUwsE4HxVtzOA+6femltQgAI1CbzIij0dkOI7aX4qElCEq4OG4pqzZL/3n5cmgQZAL/Hqtyq+c+ljTSmcxP0AABWLSURBVJebuB7ghX1sy02GFpBbjWL7HPnvhw7BgRSgQCkCGbL/VsFpAF5QSkAGWZDAQ16z1wKzbm4LUdQNQADOVnU7ApjVL3iGbAMVFI9j5C0v/aINt91sVdk3IP8WAB0uBEdRgAKjCBhk+4rgcAB2lDgc24eA6nYe/sw+tkxmk3gbANHjffDvB+AH1TTIviCCLw46jtsPLhCAi1Rd8UKR2wYfzREUoMCQAsuJZMcYoHh8Nz8VC4jgGy644pboVn2ibABE8BUX3KdGkDYi2fl8SNAIgoMNfRgqH/XIfzDYMG5NAQoMKmDR2wOiXwOwxKBjuf0wAnqVV//mtnzvP69AdA2AKj4V4L4yzDLNN2YZK9kfACxfQiyG6EMgAOeouuKszd19bM5NKECBgQSmryTivmuAjQYaxo1HEfi312zNBd19NkrgGMbG1AB4qLzfIz++LJgM2boquBhAVlZMxplS4D6oftDD/3jKLbkBBSjQj4Ax6H1YRA8DsGg/A7hNKQK5KDZ2cJeUEi3CILE0AMWz53f08GeXbWSQfUIExekyfuoUEDnVh/zDvF2wTnTO1T6BsVda8cfxcef1r6yq7BWQH1P/zPXNGEMD8PDE2+cq67KsscdA5QP1sXKmCYG7oPo+D188pZEfClCgf4Fs4gr/4iU+0/ofxi1LEWjRw34W5tF0A3CPUdksR148y7/KTyaSnceLAqskXkjsuWcDPgngzoYy4LQUSEagh95rvPjvC8waySTdokQn7mwqHjznWlTWpKU02ADoLV6zjYHZ/6gJefFMshkKrFbTfJzmmQKPquLgAHcUgJw4FKDAswSmZSb7QnEhNK9bamrvKB4579fqyleXjTQAivCXoGHT+n8jnL6SFXcln5jV1A8XIMCNUOzt4IqHNfFDAQrMOdpnb4TgOAVWJUhjAg97NWsD4zc0lkHNEzfQAOgMr34LAA/UXOuc6XrorRVEfw1gehPzc865AgE4Q9V9gg8Q4h7RcYFlrbEHTFyjxKeXNrczBKhu2bXrlWptAAJwnqrbAcDjza1z8cxMuwNEfsjXBze5CnPmflwVhwW4rwKY3Xg2TIAC9Qk8LzPZvqr4OG/tqw99QTOp4pMBrnN3i9XXAIic7EP+nlgurDDI9hNBcV8tP40L6D+g+GjXuu/G2ZlAEwLTDHofEtHi1eXPbyIBzjmfgOixPvg9u+hSSwMw8Rzlj8X20hhr7PehsnsXFz7GmgPwi0zl8zny4joNfijQJgFjYXeBmIMAXbFNhaVcy8QL57Yb5p0zKdf9ZO6VNwCq+HyAOyRSrJ5IdoEB/jvS/DqZVvFI4UzlCzny4lHO/FAgaQELu4WKHiYwr0q6kNYlr5d59RsP8rbZthFU2QAEVfmfgPzoyNGWzCS7XIFXRJ5n19LTuRcKmgOA8eu7VjzrTV8gQ7aOih4ByLrpV9OuChThuqChWJdGLkaPRbOqBmAcqruk8zz4aatY8ZcDWCaWhWEeTwkEiJzig/lijc+MID8FRhAYW00kHGaArUcIwqHVCdzh1b0RwB3VTZFG5CoagEdF8XYH98s0COZmWTx9K4j+iq/YjHbVHER/4IM/mLcORrtGXU/sJdbYA6HybhQ3G/ETo8ADVs264xi/Lsbk6s6p7AbgPqOyeY78qroLKWO+iWcEFA+oeW4Z8RijEoFxiB7nQ3YkzwhU4sugAwqMYew/vfEfgcpufL7IgHj1bj5r4u1+l9U7bbyzldgAyO1eZRNg/MZ4y506swzZW1TwcwDPmXprbtGgQAjAuVbx/xzcRQ3mwam7KWAt7JZBZG9eRJzEDuChur2HPyuJbGtKspQGoHi8q1O3CYDba8q70mkyZJuo4Kd8C1elzKUFV4Q/i9r/55Gf3OUreksDZaCFCSxpkL1PRD8EyEqkSkJAiycteuTfSyLbGpMsoQHQq7z6zQHcV2PelU9lYbeCyBl8KUfl1GVO8G8RHO2C+zaAu8oMzFjdFhjD2KsmTvPvzLODSe0LASrv98i/n1TWNSU7UgMQgF+qurcDeLSmfGudxsK+o7gCnRf01MpexmQ5RH5kAr6eI/99GQEZo5MCxWn+rSZO86/fSYG0iy5O+7/bwxdnBvmZRGD4BkDkxz7kuwAYb7OshX03RI7newNSXWW9QtUcH5D/CMCDqVbBvGsVWGruaX75EJ/aV6t7mZPlUN05nVvRyyy9/1jDNQCiR/vg/2fuS93a/zHofVBEi9PK/KQrMBsiP0UIJ3j482N5J0W6nO3LvIfea4MJH4RKcZp/kfZV2JmKiufQ7ODhi+u4+FmIwMANgAgOccF9vmuqBtk+IijeWsdP+gL3iOBUCXJCjvya9MthBcMK9NBbU41ur6rbAbLKsHE4LhqB4la/4jk0RZPPzxQCgzQAqiofC8i/0VVVg+zzIjioq/W3sW5F+AvUnBDgiu8J72xjjazpGQJSPKIXBtupynaArkCf1gg8LootHdzFramo4kL6bQAcVN/DiymAzGSHqOJzFa8Lw9cvUDxX4CJROSsgPxfArfWnwBkrErAZsnWL3/ShUly0vHxF8zBscwKPiOJtDu7S5lJIb+Z+GoDHJ75POS+98qrJ2CDbVwRfriY6o8YgUJwZMGJ+hoBzHVzxnggfQ17MoW+BLEO2gRrdDirbAHhB3yO5YWoCDxqVzfga8cGXbaoG4AFRbOHgZgweut0jLHrvg+gxAEy7K2V1AO6HyM8RwrkTFxB2+g1iEe8RYxZ2YxgUv+lvBWCpiHNlauUIFI+f34TX8gyHubAG4E6rZtNxjP9luNDtH2Vht4dI8d3xWPurZYUTAh7Q36rKuRZyYY78T125GybCPWCJDNnaMHiTV6xjgLUALBphnkypGoF7rJqNxjH+52rCtz/qAhoA/YfX3sbArFvaTzBahRmyjVXwE/6PZzTHhEc/EoArrWAGAmY4uCsAPJRwPRGnPu1lFq64gO9NqrqOwKzO53NEvFzVpnaXV7MhMH5DtdO0O/qzGgBFuDZo2AzAPe0uvbzqeuitHUSLaySWLC8qIyUqEBThehEpGoLfemQz+NbCoVZyWobsdQFYRwVvMsA6/B5/KMcWDipePGc24M/V6Es7XwOgl3j1xXdnD48eulsR5rwSVMKFAJbrVuWstg+BewMwQxRXC/R6D3sDMP53AHkfY7uwiQB4sYV9nRhZR1XfBMjr+DKuLiz9oDXqP732NuDZ6UHdJt/+qQYgAGeruh35NrVRYKevbCX/BSArjxKFYzshkAvwDw9cbwU3aNDrDcz1OfK/tvRncBow9lILv4rCrGKMruIVq1hgFQVeyoN9J/b5kYoU4O9O3QYA7hgpEAc/JTC3ARA93gf/ft7qVMqesawRc6HAvKqUaAzSNYEA6M0BcoMV/CMEzBToXQK5y8DMHMd48ZbD+wFohDBL9tBbJSCsopBVxOgqQWVlM+cJe/pifl8f4YolkpIA1zt1GwKYmUjKSaQpmcm+7IL7VBLZppPkklbsuYC8MZ2UmWlCAuOA3A2EuwJkphG9S4PcBcg9gvD4xBmEJwQyq/hngcz55/E5/z67+G9PTGxT/HNx+n2xuX+NLdaDLqbQRRU68d/MYjrnz3RRY1D82Zz/HlSKvy9q5m7/PIEpnqjHa2AS2onSSVV/59VvAeDedHJOI9Pih5+fagQWFclON0BxQSU/FKAABSgwoEAATld1u000rQOO5uZTCbABmEpotD+3mcmOVMXeo4XhaApQgALdEhDB4S644rHrMX7d1YrFYANQwzJOPDWweJ1wr4bpOAUFKECBlAVyqOzpkR+fchEp5M4GoKZVmvMyEsEZAJapaUpOQwEKUCA1geLx89s6uF+nlniK+bIBqHXVpq9kZPxsgfmvWqflZBSgAAWiFyieQJu9DZj9t+hTbUmCbADqX8jFRLITDVC8oYwfClCAAhSAXurVF69qvo8Y9QmwAajPet6ZitsvD1LF/s1Mz1kpQAEKRCIgcoIPefEcmvFIMupMGmwAGlxqC/tOiBQXuizSYBqcmgIUoEATArmqfCIg/1YTk3POuQ8B4adBgR56rwuiZwN4UYNpcGoKUIACdQr8SxQ7OLjL65yUcz1TgA1AHHvEslbsWYAU7zPnhwIUoEBrBQJw8cR7Z/hkv4ZXmQ1Awwswz/TTrLFfh8pe8aTETChAAQqUJqAi+JILrrj2yZcWlYGGFmADMDRdNQMt7HYQ+R6AJaqZgVEpQAEK1C7wEFTf7eGLrzv5iUSADUAkCzFfGitasacAsk6c6TErClCAAv0JKMKfg/a2BWb/o78R3KouATYAdUkPPk+WmexAVewHwAw+nCMoQAEKNCww9xa/DwIo3lLJT2QCbAAiW5D508mQbaCCkwAsF3mqTI8CFKDAkwLFKf8PefhTSBKvABuAeNdm3syeL5L9nwHemka6zJICFOiuwJyn+u0K4NbuGqRRORuANNapyFIMeh8T0SMAjKWTNjOlAAU6IuBUcWCAOxxA6EjNSZfJBiCx5SseHKSipyrw8sRSZ7oUoEBLBQT4u6jsnCO/qqUltrIsNgBpLuti1vS+DdXiNBs/FKAABZoTEP2eD/5jAB5rLgnOPIwAG4Bh1CIZY2F3gMg3AbwwkpSYBgUo0B2B+6D6fg//k+6U3K5K2QCkv55LWdM7snjIRvqlsAIKUCAFgQCcreo+BODOFPJljpMLsAFoyZ6RIdtYRY8FZKWWlMQyKECB+ATuhupHPPyP40uNGQ0qwAZgULG4t180M9khqtibDw+Ke6GYHQWSExD9vg/+kwAeSC53JjypABuAFu4YPfTW8uKPE5jVW1geS6IABWoV0JtE5QMO7uJap+VklQuwAaicuLEJxgyy/UTwWT43oLE14MQUSFnAi+BIF9wBAJ5IuRDmPrkAG4DW7xljq1nxxwGydutLZYEUoEApAopwrVX7vhz5NaUEZJAoBdgARLkspSdlDHofFtHDACxaenQGpAAF2iLwiCoOCnBfB+DaUhTr4BkA7gPACtb0vgzVdxKDAhSgwDwCirlv7vsMgJmU6YYAzwB0Y52fUWWGbB0VPRKQtTpYPkumAAWeIaBXGjV758h/R5huCbAB6NZ6z1utWNh3QczhgK7QXQZWToHOCsyE6mc8/AkAtLMKHS6cDUCHF3+i9OkG2T4iKE79LUYOClCg9QLjIvi6C+4QAI+0vloWuEABNgDcOZ4UWNYae8j/b+9cQuSoojD8nVvdnQkRHxiZIAoK6gxofICQEePCB5osfCxESVBUUEKiGxciRgUXLqISBBWJLrJJEESQiOIDTUAh4Bh1JROE+BqJT5wohDymq+6RmmAgoNBxpmZuVf2LpuZx69z//07R/dNdfS9u92kRIV0UItBMAhHecc8ehqP7mulQrk6GgALAydBqwdgu3cty880Brm+BXVkUgZYQ8D3mtjEn/6glhmVzAAIKAANAauOQjOxmM3vOYaSN/uVZBJpAwGDC3Z8sKN5sgh95mFsCCgBzy7Np1bqB7nozL1cT1JbDTeuu/DSYgH+H81RBsR2IDTYqa7MgoAAwC3gtOnVxoLvOzB8Bzm6Rb1kVgboR+MXdno70XwX6dRMvvfNLQAFgfnnXfbZFge79ZjwKfm7dzUi/CDSIwAF3nonkLwKHGuRLViokoABQIdwGl+4FuveaxcfAzmuwT1kTgdQJHDDjpTzmm4G/UhcrfWkRUABIqx91U9PJ6N6NxY1gF9RNvPSKQI0J7Hfn+Uj+CnCwxj4kfQEJKAAsIPwGTZ1lZGvN7HF9a6BBXZWV5AgYfO1uzxb0y5v7ppMTKEG1IqAAUKt2JS82ZGR3uPkTRrg4ebUSKAK1IeB7cDYVFDt0V39tmpa8UAWA5FtUS4HlPgO3RrOHtKBQLfsn0YkQiPBh5mzKyXclIkkyGkRAAaBBzUzTSm+0E+J6d+4BTktTo1SJQFIEjmD2eoi80Kf/ZVLKJKZRBBQAGtXOpM0sCXTvwooNRrg0aaUSJwILQsC/dbctkXwr8MeCSNCkrSKgANCqdqdhtkNnpQfbgPvtQDcNVVIhAgtCIEZ4N7i/XFC8r215F6QHrZ1UAaC1rU/C+HCg84AZ64BzklAkESIwPwR+N2NrHjtb4Mj38zOlZhGBEwkoAOiKSIFA+TXCW6LZgwGuA3RdptAVaaiAgO/G2VJQvAEcrWAClRSBgQnoiXZgVBo4PwQWXRAo1gZjrdYUmB/imqVqAr7P3bZHsu1w9JuqZ1N9ERiUgALAoKQ0bt4JdOle4cHXutud2ntg3vFrwtkR+APz10MM2/r0P51dKZ0tAtUQUACohquqzi0B69C5xoOvwa28cXDp3JZXNRGYEwJHI7wd3LcVFO9pN745YaoiFRJQAKgQrkpXQqCTkd1ICGtwvw04pZJZVFQEBiNQRPgkuL1W0C8/19eGPINx06gECCgAJNAESfjfBBZnZDdHszUBVgOL/nclnSgCgxM4FOGD4L6joHgHmBr8VI0UgXQIKACk0wspmR2B0zOymwhhNe43ActmV05ni8AJBH7H/G0ibxUUHwKHxUcE6k5AAaDuHZT+fyNgXbqXF/gqM18NdhXQESoRODkC/q2Z7SCyIyffrU14To6eRqdPQAEg/R5J4ewJnJaR3UBgFW6rtOjQ7IE2tMJfET42t50R+wimJxrqU7ZEYIaAAoAuhNYR6NG7JCeudmNVgJVAr3UQZLgkcDjCbnN2ZtiuPv0vgEJoRKAtBBQA2tJp+fwvAqdkZNdasKvdfQzsSmCJcDWSQB/8MzPbRWRnTl5+P1+r8TWy1TI1CAEFgEEoaUybCGRdussLGLPAmLmPOVykd8tqeQn8HGHcnPEA4zn5HuBgLZ1ItAhUQEABoAKoKtk4Amd06KwgMFY4YwFWAKc3zmW9DR0C/9zMxj36eEHxGfBjvS1JvQhUS0ABoFq+qt5MAga9kQwfI8QVOMvBRoEzm2k3OVdT4HsxJjyGzzMY79P/Sp/fJ9cnCUqcgAJA4g2SvFoRWNqhM+rYiAUfLZzRgI+CnQ9ktXKShthfI0wE8/KFfm/AJ3Ly8s78X9OQJxUiUG8CCgD17p/U14NAr0fvwoJixLFRCzaKxzIYjACn1sNCJSoj8BP4JBYmDZ/0aPvs2Av9Xq2wVwlzFRWB4wQUAHQxiMDCEjirR29ZJA47PuzYshCYOUb3YSMOG6Fc1bDcAKlO7yKUX6f70+C3AiaD+Q8ebeZF3rAfcjqTcGS/NsxZ2ItPs7ebgAJAu/sv9/UhEMoQ8C9hobwZccjxofIIYSj6Pz8zFPDj/zNsiJlHOe74o3wOmD7x4dOGTUfizN/Ln8tjPHY8FMynDJuKsVwD3w4Yceb38tEnm4Ij5dr45aY4Xh+8UioC7SPwN8v78C4+Pfm5AAAAAElFTkSuQmCC"));
    }
    QIcon InfoIcon(in);
    ui->Reload->setIcon(InfoIcon);
    ui->Header->setStyleSheet("color: "+preview["text"].toString());
    ui->CloseBox->setStyleSheet("color: "+preview["text"].toString()+"; border-radius: 10px; background: "+preview["buttons"].toString());
    ui->Console->setStyleSheet("color: "+preview["text"].toString()+"; border-top-left-radius: 20px; border-top-right-radius: 0px;border-bottom-right-radius: 0px;border-bottom-left-radius: 0px; background: "+preview["buttons"].toString());
    ui->ThemeEditor->setStyleSheet("color: "+preview["text"].toString()+"; border-radius: 0px; background: "+preview["buttons"].toString());
    ui->OpenLogs->setStyleSheet("color: "+preview["text"].toString()+"; border-top-left-radius: 0px;border-top-right-radius: 20px;border-bottom-right-radius: 0px;border-bottom-left-radius: 0px; background: "+preview["buttons"].toString());
    ui->CloseBox->setStyleSheet("color: "+preview["text"].toString()+"; border-radius: 10px; background: "+preview["close"].toString());
    ui->Discord->setStyleSheet("color: "+preview["text"].toString()+"; border-top-left-radius: 0px;border-top-right-radius: 0px;border-bottom-right-radius: 0px;border-bottom-left-radius: 20px; background: "+preview["buttons"].toString());
    ui->LR->setStyleSheet("color: "+preview["text"].toString()+"; border-radius: 0px; background: "+preview["buttons"].toString());
    ui->GH->setStyleSheet("color: "+preview["text"].toString()+"; border-top-left-radius: 0px;border-top-right-radius: 0px;border-bottom-right-radius: 20px;border-bottom-left-radius: 0px; background: "+preview["buttons"].toString());
    ui->frame->setStyleSheet("border-radius: 25px; background: "+preview["textbox"].toString());
    ui->OffsetBox->setStyleSheet("background:transparent;color: "+preview["text"].toString());
    ui->LogBox->setStyleSheet("background:transparent;color: "+preview["text"].toString());
    ui->PrinterBox->setStyleSheet("background:transparent;color: "+preview["text"].toString());
    ui->OpenThemes->setStyleSheet("color: "+preview["text"].toString()+";border-top-left-radius: 10px;border-top-right-radius: 0px;border-bottom-right-radius: 0px;border-bottom-left-radius: 10px;background: "+preview["buttons"].toString());
    ui->Reload->setStyleSheet("color: "+preview["text"].toString()+";border-top-left-radius: 0px;border-top-right-radius: 10px;border-bottom-right-radius: 10px;border-bottom-left-radius: 0px;background: "+preview["buttons"].toString());
    ui->intervalTextBox->setStyleSheet("color: "+preview["text"].toString()+";border-top-left-radius: 10px;border-top-right-radius: 0px;border-bottom-right-radius: 0px;border-bottom-left-radius: 10px;background: "+preview["buttons"].toString());
    ui->intervalTextBox_2->setStyleSheet("color: "+preview["text"].toString()+";border-top-left-radius: 0px;border-top-right-radius: 10px;border-bottom-right-radius: 10px;border-bottom-left-radius: 0px;background: "+preview["buttons"].toString());
    ui->Background_2->setStyleSheet("border-radius: 25px; background: "+preview["background"].toString());
    ui->offsetPos->setStyleSheet("color: "+preview["text"].toString());
    ui->X->setStyleSheet("color: "+preview["text"].toString());
    ui->Y->setStyleSheet("color: "+preview["text"].toString());
    ui->opt->setStyleSheet("color: "+preview["text"].toString());
    ui->themes->setStyleSheet("color: "+preview["text"].toString());
    ui->ThemeCombo->setStyleSheet("background: "+preview["buttons"].toString()+"; color: "+preview["text"].toString());
}

void SettingsWindow::reloadList(){
    ui->ThemeCombo->clear();
    QList list(QStringList()<<"dark"<<"light");
    QDirIterator it(PathAD+"/themes/", QStringList() << "*.drawtheme", QDir::Files, QDirIterator::Subdirectories);
    while (it.hasNext()){
        it.next();
        QString fileName = it.fileName().replace(".drawtheme", "");
        if (fileName != "light" && fileName != "dark"){
            list << fileName;
        }
    }
    list << "Get more!";
    ui->ThemeCombo->addItems(list);
    QFile inFile(PathAD+"/user.cfg");
    inFile.open(QIODevice::ReadWrite|QIODevice::Text);
    QByteArray data = inFile.readAll();
    QJsonParseError errorPtr;
    QJsonDocument doc = QJsonDocument::fromJson(data, &errorPtr);
    QJsonObject doc_obj = doc.object();
    ui->ThemeCombo->setCurrentIndex(ui->ThemeCombo->findText(doc_obj["theme"].toString()));
    inFile.close();
}

void SettingsWindow::on_GH_released()
{
    QDesktopServices::openUrl(QUrl("https://github.com/AlexCYP/autodraw-roblox"));
}


void SettingsWindow::on_LR_released()
{
    QDesktopServices::openUrl(QUrl("https://github.com/AlexCYP/autodraw-roblox/releases/latest"));
}


void SettingsWindow::on_Discord_released()
{
    QDesktopServices::openUrl(QUrl("https://discord.gg/rwvUFraDnb"));
}


void SettingsWindow::on_CloseBox_released()
{
    this->close();
}

void SettingsWindow::on_OpenThemes_released()
{
    QDesktopServices::openUrl(PathAD+"/themes/");
}


void SettingsWindow::on_Reload_released()
{
    indexReady = false;
    reloadList();
    indexReady = true;
    QFile inFile(PathAD+"/user.cfg");
    inFile.open(QIODevice::ReadOnly|QIODevice::Text);
    QByteArray data = inFile.readAll();
    QJsonParseError errorPtr;
    QJsonDocument doc = QJsonDocument::fromJson(data, &errorPtr);
    QJsonObject rootObj = doc.object();
    QString theme = rootObj.value("theme").toString();
    reloadThemes(theme);
    inFile.close();
}

void SettingsWindow::on_ThemeCombo_currentIndexChanged()
{
    if (!indexReady) return;
    QString Item = ui->ThemeCombo->currentText();
    QFile inFile(PathAD+"/user.cfg");
    inFile.open(QIODevice::ReadWrite|QIODevice::Text);
    QByteArray data = inFile.readAll();
    QJsonParseError errorPtr;
    QJsonDocument doc = QJsonDocument::fromJson(data, &errorPtr);
    QJsonObject doc_obj = doc.object();
    if (Item == "Get more!"){
        indexReady = false;
        ui->ThemeCombo->setCurrentIndex(ui->ThemeCombo->findText(doc_obj["theme"].toString()));
        downloadthemes *w = new downloadthemes();
        w->show();
        inFile.close();
        indexReady = true;
    }
    else{
        doc_obj.insert("theme", Item);
        QJsonDocument new_doc(doc_obj);
        inFile.resize(0);
        inFile.write(new_doc.toJson());
        inFile.close();
        on_Reload_released();
        QApplication::closeAllWindows();
        QProcess::startDetached(qApp->arguments()[0], qApp->arguments());
    }
}

void SettingsWindow::on_OffsetBox_released()
{
    if (!indexReady) return;
    QFile inFile(PathAD+"/user.cfg");
    inFile.open(QIODevice::ReadWrite|QIODevice::Text);
    QByteArray data = inFile.readAll();
    QJsonParseError errorPtr;
    QJsonDocument doc = QJsonDocument::fromJson(data, &errorPtr);
    QJsonObject doc_obj = doc.object();
    if (ui->OffsetBox->checkState()) doc_obj.insert("offset_enabled", true); else doc_obj.insert("offset_enabled", false );
    QJsonDocument new_doc(doc_obj);
    inFile.resize(0);
    inFile.write(new_doc.toJson());
    inFile.close();
    ui->intervalTextBox->setEnabled(ui->OffsetBox->checkState());
    ui->intervalTextBox_2->setEnabled(ui->OffsetBox->checkState());
}

void SettingsWindow::on_LogBox_released()
{
    if (!indexReady) return;
    QFile inFile(PathAD+"/user.cfg");
    inFile.open(QIODevice::ReadWrite|QIODevice::Text);
    QByteArray data = inFile.readAll();
    QJsonParseError errorPtr;
    QJsonDocument doc = QJsonDocument::fromJson(data, &errorPtr);
    QJsonObject doc_obj = doc.object();
    if (ui->LogBox->checkState()) doc_obj.insert("logs", false); else doc_obj.insert("logs", true);
    QJsonDocument new_doc(doc_obj);
    inFile.resize(0);
    inFile.write(new_doc.toJson());
    inFile.close();
}


void SettingsWindow::on_OpenLogs_released()
{
    QDesktopServices::openUrl(PathAD+"/logs/");
}


void SettingsWindow::on_PrinterBox_released()
{
    if (!indexReady) return;
    QFile inFile(PathAD+"/user.cfg");
    inFile.open(QIODevice::ReadWrite|QIODevice::Text);
    QByteArray data = inFile.readAll();
    QJsonParseError errorPtr;
    QJsonDocument doc = QJsonDocument::fromJson(data, &errorPtr);
    QJsonObject doc_obj = doc.object();
    if (ui->PrinterBox->checkState()) doc_obj.insert("printer", false); else doc_obj.insert("printer", true);
    QJsonDocument new_doc(doc_obj);
    inFile.resize(0);
    inFile.write(new_doc.toJson());
    inFile.close();
}


void SettingsWindow::on_Console_released()
{
    ConsoleWindow *cw = new ConsoleWindow("openWindow");
    cw->show();
}


void SettingsWindow::on_ThemeEditor_released()
{
    ThemeEditor *te = new ThemeEditor();
    te->show();
}


void SettingsWindow::on_intervalTextBox_textChanged(const QString &arg1)
{
    if (!indexReady) return;
    QFile inFile(PathAD+"/user.cfg");
    inFile.open(QIODevice::ReadWrite|QIODevice::Text);
    QByteArray data = inFile.readAll();
    QJsonParseError errorPtr;
    QJsonDocument doc = QJsonDocument::fromJson(data, &errorPtr);
    QJsonObject doc_obj = doc.object();
    doc_obj.insert("offset_x", ui->intervalTextBox->text().toInt());
    QJsonDocument new_doc(doc_obj);
    inFile.resize(0);
    inFile.write(new_doc.toJson());
    inFile.close();
    ui->intervalTextBox->setEnabled(ui->OffsetBox->checkState());
    ui->intervalTextBox_2->setEnabled(ui->OffsetBox->checkState());
}


void SettingsWindow::on_intervalTextBox_2_textChanged(const QString &arg1)
{
    if (!indexReady) return;
    QFile inFile(PathAD+"/user.cfg");
    inFile.open(QIODevice::ReadWrite|QIODevice::Text);
    QByteArray data = inFile.readAll();
    QJsonParseError errorPtr;
    QJsonDocument doc = QJsonDocument::fromJson(data, &errorPtr);
    QJsonObject doc_obj = doc.object();
    doc_obj.insert("offset_y", ui->intervalTextBox_2->text().toInt());
    QJsonDocument new_doc(doc_obj);
    inFile.resize(0);
    inFile.write(new_doc.toJson());
    inFile.close();
    ui->intervalTextBox->setEnabled(ui->OffsetBox->checkState());
    ui->intervalTextBox_2->setEnabled(ui->OffsetBox->checkState());
}

